version: "3.9"

services:
  db:
    image: postgres:14.2
    restart: always
    container_name: ctf_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432" # TODO: remove me in production
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    container_name: ctf_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
